# Generated by Django 5.0.2 on 2024-02-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_recipe_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='description',
        ),
    ]
