# Generated by Django 5.0.2 on 2024-02-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0004_remove_ingredient_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='views',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
